/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Memory Layout
	Write a program that prints the addresses of a local variable, a global variable, a static variable, and a malloc'd pointer.
	Draw the memory map from the output. Then explain in your notes why malloc is dangerous on a microcontroller with 64KB RAM.
 * */

#include <stdint.h>
#include <stdlib.h>

static uint8_t staticVar = 0;
uint8_t globalVar = 0;
const uint8_t constVar = 0;


int main(void)
{
    uint8_t localVar = 0;

    uint8_t* pMalPtr = (uint8_t*)malloc(sizeof(uint8_t));  //SRAM1 - heap area

    uint8_t* pStaticVar = &staticVar;		//SRAM1 beginning - .bss
    uint8_t* pGlobalVar = &globalVar;		//SRAM1 beginning - .bss
    uint8_t* pLoaclvar = &localVar;			//SRAM2 - stack area
    uint8_t* pPMalPtr = &pMalPtr;			// ptr that stores the location of ptr to heap: SRAM2 - stack area

    uint8_t* pConstVar = &constVar;			//Flash memory

    free(pMalPtr);
    return 0;
}
