/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
# STM32F407G-DISC1 — EXTI Button LED Blink Pattern

A bare-metal STM32 project that detects a button press using EXTI (External Interrupt) on PA0 and blinks the green LED on PD12 in patterns defined by a const lookup table.

---

## What This Project Does

- Detects button press via EXTI0 (rising edge trigger)
- Each press cycles through a blink pattern: 1, 2, 3, 4 blinks
- Pattern is selected from a `const` lookup table stored in Flash
- Debounce handled in software inside the ISR

---

## Hardware

| Pin  | Function       | Notes                          |
|------|----------------|--------------------------------|
| PA0  | USER Button B1 | External pull-down on board, no internal PUPD needed |
| PD12 | Green LED      | Push-pull output               |

---

## Key Concepts Covered

- **EXTI** — External interrupt triggered on rising edge (0→1) since button has pull-down
- **SYSCFG clock** — Must be enabled before `Interrupt_Init` to map PA0 to EXTI0
- **Debouncing** — Short delay in ISR lets bounce settle before reading pin state
- **EXTI_PR pending bit** — Cleared at end of ISR with write-1-to-clear, prevents re-triggering
- **volatile** — Used on `flag` and `count` since they are shared between ISR and main loop. Without it, compiler optimization (-O2/-O3) caches them in CPU registers and main loop never sees ISR updates
- **const lookup table** — Array placed in Flash, not RAM. Index selected with `count % 4` to cycle patterns

---

## Compiler Optimization Note

This project behaves differently under optimization:

| Level | Behavior |
|-------|----------|
| `-O0` (Debug) | Works even without `volatile` — no caching |
| `-O2` / `-O3` | Breaks without `volatile` — compiler caches `flag` in register, main loop never sees ISR write |

Always use `volatile` for variables shared between an ISR and main code.

---

## Startup Note

Add a small delay at the start of `main` when running without the debugger. On power-on the CPU starts instantly and peripherals need a moment to stabilize. The debugger's attach process accidentally provides this delay, which is why code can work in debug but not in run mode.
*/


#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "rcc.h"
#include "exti.h"
#include "gpio.h"

volatile uint8_t count = 0;
volatile uint8_t flag = 0;

const uint8_t blinkPattern[] = {1,2,3,4};

void delay(void)
{
	for(uint32_t i = 0; i < 500000; i++);
}

void debounce(void)
{
    for(uint32_t i = 0; i < 50000; i++);  // 10x shorter
}

void blinkLed (GPIO_Handle_t* peri, uint8_t times)
{
	for(uint8_t i = 0; i < times; i++)
	{
		GPIO_Led_ON(peri);
		delay();
		GPIO_Led_OFF(peri);
		delay();
	}
}

int main(void)
{
	GPIO_Handle_t button, led;
	Interrupt_Handle_t buttonInt;

	RCC_AHB1_Init(GpioA, ENABLE);

	button.GPIOx = GPIOA;
	button.pinConfig.GPIO_mode = GPIO_input;
	button.pinConfig.GPIO_pinNum = GPIOPin0;
	button.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	GPIO_Init(&button);


	RCC_AHB1_Init(Syscfg, ENABLE);
	buttonInt.Exti_triggerMode = EXTI_RISING_TRIGGER_ONLY;
	buttonInt.pGpioHandle = &button;

	Interrupt_Init(&buttonInt);
	NVIC_IRQConfig(EXTI0, ENABLE);
	NVIC_IRQPriorityConfig(EXTI0, EXTI0_PRIORITY);

	RCC_AHB1_Init(GpioD, ENABLE);

	led.GPIOx = GPIOD;
	led.pinConfig.GPIO_pinNum = GPIOPin12;
	led.pinConfig.GPIO_mode = GPIO_output;
	led.pinConfig.GPIO_ospeed = GPIO_high;
	led.pinConfig.GPIO_otype = GPIO_pushPull;
	led.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	GPIO_Init(&led);

	while(1)
	{
		if(flag)
		{
			uint8_t times = blinkPattern[count%4];
			blinkLed(&led, times);
			flag = 0;
		}

	}
	return 0;
}

void EXTI0_IRQHandler(void)
{
	debounce();
	if(GPIOA->GPIO_IDR & (1<<0))
	{
		count++;
		flag = 1;
	}

	EXTI->EXTI_PR |= (1 << 0);
}
